### ISSUE TITLE
Cant select alternate equipment

### ISSUE THREAD

**Issue by SoundSherpa** [HadaIonut/Equipement-Paper-Doll#1]
Cool mod!
Cant seem to change the item in a slot after saving the first one there. For instance, if I want to change the helm on a character.

**Comment by HadaIonut** [comment]
If you right click an item a context menu should pop up to remove the item from the slot

**Comment by SoundSherpa** [comment]
Hmm It doesnt seem to work for me. Right clicking, middle clicking, or left clicking after Ive already saved an item to a slot and I see no context menu.

Windows 10
Brave Browser
Foundry 7.9
DnD 5e 1.2.4

Im hosted in Forge if that matters.

**Comment by HadaIonut** [comment]
If you open the developer console do you see any errors?

**Comment by SoundSherpa** [comment]
I forgot to mention that but no, with console open I see no errors nor messages. Its as if it doesnt register the click there. Tried this with all mods disabled except equipment mod and dependencies.

**Comment by V3rotti** [comment]
There is no way to delete an Item from a assigned slot or choose another item on the assigned spot.

**Comment by HadaIonut** [comment]
Fixed in the next update

**Comment by SoundSherpa** [comment]
Works now thanks!
