### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by BoTKaPyC** [HadaIonut/Equipement-Paper-Doll#11]
When I turn on the mod, the character sheet breaks on the screenshots you can see this. Please fix a good mod, I use PF 2e.
![Desktop Screenshot 2021 03 25 - 21 05 10 16](https://user-images.githubusercontent.com/80960291/112505200-5e3fd680-8dae-11eb-9890-c07fcfd2e6c6.png)

![Desktop Screenshot 2021 03 25 - 21 05 36 44](https://user-images.githubusercontent.com/80960291/112505051-38b2cd00-8dae-11eb-9046-3f8010cca622.png)

**Comment by HadaIonut** [comment]
I only support DnD 5e.
