### ISSUE TITLE
Adding items forces restart of session sometimes

### ISSUE THREAD

**Issue by SoundSherpa** [HadaIonut/Equipement-Paper-Doll#2]
Seems that adding items to slots restarts the session entirely sometimes. If I find an item that causes this, it seems to be repeatable.

Windows 10
Brave Browser
Foundry 7.9
DnD 5e 1.2.4

**Comment by HadaIonut** [comment]
Could you tell me what items do that? 

Maybe provide a json export of that item.

**Comment by SoundSherpa** [comment]
After some poking around it seems that so far it's all custom items I've created rather than ones pulled from compendiums. Maybe it has something to do with the image size or proportions attached to the items? I've included json exports of a few. 
[Broken Items.zip](https://github.com/HadaIonut/Equipement-Paper-Doll/files/6150109/Broken.Items.zip)

**Comment by HadaIonut** [comment]
Hi, i still cannot reproduce this error but could you try to update to this version and tell me if it still happens

https://github.com/HadaIonut/Equipement-Paper-Doll/releases/download/1.0.4/module.json

**Comment by SoundSherpa** [comment]
I think the updates fixed this. I get no crashes and it seems to work as intended now. Thanks!
