### ISSUE TITLE
Z-index on background

### ISSUE THREAD

**Issue by Ikabodo** [HadaIonut/Equipement-Paper-Doll#3]
![image](https://user-images.githubusercontent.com/7766890/111225056-96d9f600-85df-11eb-9023-73c3b2aa0a29.png)
Maybe the image should be behind the boxes?

**Comment by HadaIonut** [comment]
The image is behind the boxes but the gray ones are transparent 

I'll think of something to make this look better

**Comment by HadaIonut** [comment]
Will get fixed in the next update
