### ISSUE TITLE
On some actors the options wont show

### ISSUE THREAD

**Issue by V3rotti** [HadaIonut/Equipement-Paper-Doll#5]
on Some actors the Option Button of the Sheet wont show, on others it does like normal.

![image](https://user-images.githubusercontent.com/56869989/111315890-16f56f80-8663-11eb-8e7a-e92f95985ab2.png)

![image](https://user-images.githubusercontent.com/56869989/111315969-25438b80-8663-11eb-96c7-6766e2cb341b.png)

Game System: Dungeon World

**Comment by HadaIonut** [comment]
Please give me more information. For example 
- are you on forge?
- is there a clear difference between the actors that have the settings menu and those that don't?

**Comment by HadaIonut** [comment]
Sorry I only support dnd 5e and i forgot to add that,
