### ISSUE TITLE
Can't open multiple sheets

### ISSUE THREAD

**Issue by V3rotti** [HadaIonut/Equipement-Paper-Doll#6]
When you open a sheet, then open the one of another character it won't show the sheet, instead it adds another Options button to the already opened sheet.
![image](https://user-images.githubusercontent.com/56869989/111316756-d21e0880-8663-11eb-9220-ab0bf71a9415.png)

**Comment by HadaIonut** [comment]
Sorry I only support dnd 5e and i forgot to add that to the module
